name: Build
on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: write

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: false
jobs:
  prebuild:
    strategy:
      matrix:
        include:
          - name: darwin
            os: macos-latest
            node: x64
            command: prebuildify
          - name: win32-x64
            os: windows-2022
            node: x64
            command: prebuildify
    name: Build ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    steps:
      - if: matrix.node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          architecture: ${{ matrix.node }}
      - uses: actions/checkout@v4
      - run: npm ci
      - run: npm run ${{ matrix.command }} -- ${{ matrix.args }}
      - uses: actions/upload-artifact@v4
        with:
          name: build-artifacts-${{ matrix.name }}-${{ github.run_id }}
          path: prebuilds/
          if-no-files-found: error
      - if: failure()
        run: npx shx ls -lA
  release:
    needs: prebuild
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: build-artifacts-darwin-${{ github.run_id }}
          path: prebuilds/
      - uses: actions/download-artifact@v4
        with:
          name: build-artifacts-win32-x64-${{ github.run_id }}
          path: prebuilds/
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org
      # Ensure npm 11.5.1 or later is installed
      - name: Update npm
        run: npm install -g npm@latest
      - run: npm ci --ignore-scripts
      - run: npm config set registry https://registry.npmjs.org
      - run: npm run build
      - run: npm run semantic-release
        env:
          GH_TOKEN: ${{ secrets.RELEASE_GITHUB_TOKEN }}