name: Build
on:
  push:
    branches:
      - main
concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: false
jobs:
  prebuild:
    strategy:
      matrix:
        include:
          - name: darwin
            os: macos-latest
            node: x64
            command: prebuildify
          - name: win32-x64
            os: windows-2019
            node: x64
            command: prebuildify
    name: Build ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    steps:
      - if: matrix.node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          architecture: ${{ matrix.node }}
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - run: pip install setuptools
      - run: npm ci
      - run: npm run ${{ matrix.command }} -- ${{ matrix.args }}
      - uses: actions/upload-artifact@v4
        with:
          name: build-artifacts-${{ matrix.name }}-${{ github.run_id }}
          path: prebuilds/
          if-no-files-found: error
      - if: failure()
        run: npx shx ls -lA
  release:
    needs: prebuild
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v4
        with:
          name: build-artifacts-darwin-${{ github.run_id }}
          path: prebuilds/
      - uses: actions/download-artifact@v4
        with:
          name: build-artifacts-win32-x64-${{ github.run_id }}
          path: prebuilds/
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - run: pip3 install setuptools
      - run: npm ci
      - run: npm run build
      - run: npm run semantic-release
        env:
          GH_TOKEN: ${{ secrets.RELEASE_GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}